### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by Kad001** [google-research/inksight#10]
Tried running this locally on gradio playground but keep running to this error: ModuleNotFoundError: No module named 'matplotlib'

After cloning and setting up the environment, running the app results in:

Traceback (most recent call last):
  File "/home/kad/Model-Output-Playground/app.py", line 5, in <module>
    from utils import *
  File "/home/kad/Model-Output-Playground/utils.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

**Comment by CharlieLeee** [comment]
Thank you for reaching out and for pointing this out! The error you’re seeing is likely due to missing dependencies. To resolve it, please try running pip install -r requirements.txt inside the Model-Output-Playground folder. This should install matplotlib and any other necessary packages.

We’ll make sure to update the README to include these instructions. Let us know if you run into any other issues, and thanks again for your feedback!

**Comment by amaksai** [comment]
Should be fixed now, thanks for the PR, Charlie
